# this is an optional github action that can be used to publish builds on release
name: Publish docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # you need to setup these secrets yourself ask your ta
          username: ${{ secrets.gorbunovd }}
          password: ${{ secrets.dckr_pat_9ji5xhOgDLkSYGNvIfdplvvDrtc }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: prod-frontend
          push: true
          tags: ${{ secrets.gorbunovd }}/${{ secrets.softeng-team-o }}:frontend
      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: prod-backend
          push: true
          tags: ${{ secrets.gorbunovd }}/${{ secrets.softeng-team-o }}:backend

